config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show]

  resources :events do
    resources :attendances
    resources :event_pictures, only: [:create]
    patch :update_true, on: :member
    patch :update_false, on: :member
  end

  root to: 'events#index'

  namespace :admin do
      root to: 'users#index'
      resources :users, :events, :attendances
  end

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

end

app/models/event.rb
class Event < ApplicationRecord
  has_one_attached :event_picture
  has_many :attendances, dependent: :destroy
  has_many :attendees, class_name: "User", through: :attendances
  belongs_to :administrator, class_name: "User"

  validate :start_date_cannot_be_in_the_past
  validates :duration, presence:true, numericality: {greater_than: 0}
  validate :duration_is_multiple_of_5
  validates :title, presence:true, length: {in: 5..140}
  validates :description, presence:true, length: {in: 20..1000}
  validates :price, presence:true, numericality: {in: 1..1000}
  validates :location, presence:true
 
  def duration_is_multiple_of_5
    if duration.present? && duration % 5 != 0
      errors.add(:duration, "La durée de l'évènement doit être un multiple de 5.")
    end
  end

  def start_date_cannot_be_in_the_past
    errors.add(:start_date, "La date de début ne peut pas être dans le passé.") if
      !start_date.blank? and start_date < Date.today
  end

  def end_date
    return (start_date + duration * 60)
  end

  def is_validate
    if validated
      return true
    end
  end

  def need_validation
    if validated == nil
      return true
    end
  end

  def denied
    if !validated
      return true
    end
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  include ApplicationHelper
  before_action :check_if_admin

  def index
    @events = Event.all.where(validated: nil)
  end

  def edit
    @event = Event.find(params[:id])
  end

  def show
    @event = Event.find(params[:id])
  end
  
  def update
    @event = Event.find(params[:id])
    if params['event'] == "true"
      @event.update(validated:true)
      flash[:notice] = "L'évènement a été accepté !"
      redirect_to admin_events_path
      
    else params['event'] == "false"
      @event.update(validated:false)
      flash[:notice] = "L'évènement a été refusé !"
      redirect_to admin_events_path
    end

  end

  private

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include ApplicationHelper
  before_action :authenticate_user, only: [:new, :create, :show]
  before_action :authenticate_administrator, only: [:edit, :update, :destroy]
  before_action :check_if_admin, only: [:update_true, :update_false]

  def index
    # Ne montrer que les évènements validés
    @events = Event.all.where(validated: true)
  end

  def show
    @event = Event.find(params['id'])
    if @event.attendances.count > 0 && @event.attendances.find_by(attendee_id: current_user)
      @registered = true
    else
      @registered = false
    end

  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(start_date: params['event']['start_date'],
      duration: params['event']['duration'].to_i, 
      title: params['event']['title'], 
      description: params['event']['description'],
      location: params['event']['location'],
      administrator_id: current_user.id,
      price: params['event']['price'].to_i)
    if (@event.save && params[:event][:event_picture])
      @event.event_picture.attach(params[:event][:event_picture])
      flash[:notice] = "L'évènement a bien été créé !"
      redirect_to '/'
    else
      flash[:alert] = "Erreur lors de la création de l'évènement."
      redirect_back(fallback_location: root_path)
    end
  end

  def edit
    @event = Event.find(params['id'])
  end

  def update
    @event = Event.find(params['id'])
      if @event.update(params.require(:event).permit(:start_date, :duration, :title, :description, :location, :price))
        flash[:notice] = "Votre évènement a bien été mis à jour !"
        redirect_to @event
      else
        flash[:alert] = @event.errors.full.messages[0]
        render 'edit'
      end
  end

  def destroy
    @event = Event.find(params['id'])
    @event.destroy
    flash[:notice] = "L'évènement a été supprimé"
    redirect_to root_path
  end

  private

  def authenticate_user
    unless current_user
      flash[:alert] = "Merci de vous connecter pour voir les évènements."
      redirect_to new_user_session_path
    end
  end

  def authenticate_administrator
    unless current_user == Event.find(params['id']).administrator
      flash[:alert] = "Vous ne pouvez modifier que vos évènements"
      redirect_to root_path
    end
  end

end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/index.html.erb
<h1> Evènement à gérer</h2>

<p> Il y a actuellement <%= @events.count %> évènement(s) à traiter.


<div class="card w-50">
  <div class="card-body">
    <h5 class="card-title">Evènement en attente de validation </h5>
      <table>
        <thead>
          <tr>
            <th>Titre</th>
            <th>Description</th>
            <th>Administrateur</th>
            <th>Images</th>
            <th>Voir l'évènement</th>
          </tr>
        </thead>
      <% @events.each do |event| %>
        <tbody>
        <th><%= event.title %></th>
        <th><%= event.description %></th>
        <th><%= event.administrator.first_name %> <%= event.administrator.last_name %></th>
        <th><% if event.event_picture.attached? %> <%= image_tag event.event_picture, width: "100vh", style:"border-radius: 10px;" %> <% else %> - <% end %></th>
        <th><%= button_to "Voir l'évènement", admin_event_path(event), class:"btn btn-primary", method: :get %></th>
        </tbody>
      <% end %>
      </table>
    </div>
</div>

app/views/admin/events/show.html.erb
<h1 class="mt-4"> Gestion de l'évènement n°<%= params['id'] %></h1>

<div class="card mt-4" style="width: 40rem;">
  <div class="card-body">

    <p> <span style="color: blue;">Proposé par </span><%= @event.administrator.first_name %> <%= @event.administrator.last_name %> </p>

    <p> <span style="color: blue;">Titre : </span><%= @event.title %></p>

    <p> <span style="color: blue;">Description : </span><%= @event.description %></p>

    <p> <span style="color: blue;">Date de début de l'évènement : </span><%= @event.start_date %></p>

    <p> <span style="color: blue;">Date de fin de l'évènement : </span><%= @event.end_date %></p>

    <p> <span style="color: blue;">Lieu de l'évènement : </span><%= @event.location %></p>

    <p> <span style="color: blue;">Prix : </span><%= @event.price %> euros</p> 

    <%= button_to "Valider l'évènement", admin_event_path(@event), method: :patch, params: { "event" =>  "true" }, form: {style: 'display:inline-block;'}, class:"btn btn-success m-2" %>
    <%= button_to "Refuser l'évènement", admin_event_path(@event), method: :patch, params: { "event" => "false" }, form: {style: 'display:inline-block;'}, class:"btn btn-danger m-2" %>
    <%= button_to "Supprimer l'évènement", event_path, method: :delete,form: { data: { turbo_confirm: "Veux-tu supprimer cet évènement (et rendre son créateur malheureux...) ?" }, style: 'display:inline-block;'}, class:"btn btn-dark m-2" %>

  </div>
</div>