config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show]

  resources :events do
    resources :attendances
    resources :event_pictures, only: [:create]
    patch :update_true, on: :member
    patch :update_false, on: :member
  end

  root to: 'events#index'

  namespace :admin do
      root to: 'users#index'
      resources :users, :events, :attendances
  end

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

end

app/models/event.rb
class Event < ApplicationRecord
  has_one_attached :event_picture
  has_many :attendances, dependent: :destroy
  has_many :attendees, class_name: "User", through: :attendances
  belongs_to :administrator, class_name: "User"

  validate :start_date_cannot_be_in_the_past
  validates :duration, presence:true, numericality: {greater_than: 0}
  validate :duration_is_multiple_of_5
  validates :title, presence:true, length: {in: 5..140}
  validates :description, presence:true, length: {in: 20..1000}
  validates :price, presence:true, numericality: {in: 1..1000}
  validates :location, presence:true
 
  def duration_is_multiple_of_5
    if duration.present? && duration % 5 != 0
      errors.add(:duration, "La durée de l'évènement doit être un multiple de 5.")
    end
  end

  def start_date_cannot_be_in_the_past
    errors.add(:start_date, "La date de début ne peut pas être dans le passé.") if
      !start_date.blank? and start_date < Date.today
  end

  def end_date
    return (start_date + duration * 60)
  end

  def is_validate
    if validated
      return true
    end
  end

  def need_validation
    if validated == nil
      return true
    end
  end

  def denied
    if !validated
      return true
    end
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  include ApplicationHelper
  before_action :check_if_admin

  def index
    @events = Event.all.where(validated: nil)
  end

  def edit
    @event = Event.find(params[:id])
  end

  def show
    @event = Event.find(params[:id])
  end
  
  def update
    @event = Event.find(params[:id])
    if params['event'] == "true"
      @event.update(validated:true)
      flash[:notice] = "L'évènement a été accepté !"
      redirect_to admin_events_path
      
    else params['event'] == "false"
      @event.update(validated:false)
      flash[:notice] = "L'évènement a été refusé !"
      redirect_to admin_events_path
    end

  end

  private

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include ApplicationHelper
  before_action :authenticate_user, only: [:new, :create, :show]
  before_action :authenticate_administrator, only: [:edit, :update, :destroy]
  before_action :check_if_admin, only: [:update_true, :update_false]

  def index
    # Ne montrer que les évènements validés
    @events = Event.all.where(validated: true)
  end

  def show
    @event = Event.find(params['id'])
    if @event.attendances.count > 0 && @event.attendances.find_by(attendee_id: current_user)
      @registered = true
    else
      @registered = false
    end

  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(start_date: params['event']['start_date'],
      duration: params['event']['duration'].to_i, 
      title: params['event']['title'], 
      description: params['event']['description'],
      location: params['event']['location'],
      administrator_id: current_user.id,
      price: params['event']['price'].to_i)
    if (@event.save && params[:event][:event_picture])
      @event.event_picture.attach(params[:event][:event_picture])
      flash[:notice] = "L'évènement a bien été créé !"
      redirect_to '/'
    else
      flash[:alert] = "Erreur lors de la création de l'évènement."
      redirect_back(fallback_location: root_path)
    end
  end

  def edit
    @event = Event.find(params['id'])
  end

  def update
    @event = Event.find(params['id'])
      if @event.update(params.require(:event).permit(:start_date, :duration, :title, :description, :location, :price))
        flash[:notice] = "Votre évènement a bien été mis à jour !"
        redirect_to @event
      else
        flash[:alert] = @event.errors.full.messages[0]
        render 'edit'
      end
  end

  def destroy
    @event = Event.find(params['id'])
    @event.destroy
    flash[:notice] = "L'évènement a été supprimé"
    redirect_to root_path
  end

  private

  def authenticate_user
    unless current_user
      flash[:alert] = "Merci de vous connecter pour voir les évènements."
      redirect_to new_user_session_path
    end
  end

  def authenticate_administrator
    unless current_user == Event.find(params['id']).administrator
      flash[:alert] = "Vous ne pouvez modifier que vos évènements"
      redirect_to root_path
    end
  end

end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
</br><h1> Editer l'évènement </h1></br>

<div class="card-position">
  <div class="card" style="width: 40rem;">
    <%= form_for @event do |f| %>

      <div class="form-group mt-4">
        <label>Nom de l'évènement</label>
        <%= f.text_field :title, class: 'form-control m-2' %>
      </div>

      <div class="form-group">
        <label>Description de l'évènement</label>
        <%= f.text_area :description, class: 'form-control m-2' %>
      </div>

      <div class="form-group">
        <label>Lieu de l'évènement</label>
        <%= f.text_area :location, class: 'form-control m-2' %>
      </div>

      <div class="form-group">
        <label>Date de début</label></br>
        <%= f.datetime_field :start_date, class: 'form-control m-4' %>
      </div>

      <div class="form-group">
        <label>Durée de l'évènement</label>
        <%= f.number_field :duration, min: 0, step: 5, class: 'form-control m-2' %>
      </div>

      <div class="form-group">
        <label>Prix de l'évènement</label>
        <%= f.number_field :price, min: 1, max: 1000, step: 1, class: 'form-control m-2' %>
      </div>

      </br><div class="form_group" data-turbo=false>
        <button type="submit" class="btn btn-primary m-2" form: {style: 'display:inline-block;'}> Modifier l'évènement</button>
      </div>
     <% end %>
    <%= button_to "Supprimer l'évènement", event_path, form: { data: { turbo_confirm: "Veux-tu supprimer cet évènement (et rendre des gens malheureux...) ?" }, style: 'display:inline-block;'}, class:"btn btn-danger m-3", style:"display: inline;", method: :delete %>
    
    <div>
    <% if @event.event_picture.attached? %>
      <%= image_tag @event.event_picture, width: "50%", style:"border-radius: 15px;" %>
    <% else %>
        <p>=== Il n'y a pas encore d'image liée à cet évènement ===</p>
    <% end %>
    </div>
      <h3 class="m-3">Changer La photo de l'évènement</h3>
      <%= form_tag event_event_pictures_path(@event), multipart: true do %>
        <%= file_field_tag :event_picture %>
        <%= submit_tag "mettre à jour", class:"btn-pic" %>
        </br></br>

    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<h1 class="mt-3">Ben alors.... Oukonva ?</h1>
  <p> Tu te poses cette question ? Alors tu es au bon endroit !</p>
  <p> Voici les évènements prévus dans ta ville : </p>

  <div class="card-position row", style="width:100%">

    <% @events.reverse_each.with_index do |event, index| %>
      <div class="card card-spec m-3" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"><%= event.title %></h5>
          <h6 class="card-subtitle mb-2 card-text"><%= event.description %></h6>
          <p class="text-muted">Date : <%= event.start_date.strftime("%d %B %Y, %H:%M") %></br>
          Nombre d'inscrit : <%= event.attendees.count %></br>
          Tarif : <%= event.price %> euros </br>
          Hôte : <%= event.administrator.first_name %> <%= event.administrator.last_name %></p>
          <% if event.event_picture.attached? %>
          <%= image_tag event.event_picture, width: "80%", style:"border-radius: 10px;" %>
          <% end %>
          <%= button_to "Détails de l'évènement", event_path(event), class:"btn btn-dark mt-4 m-2",method: :get %>
        </div>
      </div>
    <% end %>
  </div>



<h2 class="p-4"> Tu veux créer un évènement ? N'hésites pas ! </h2>
<div><%= button_to "Nouvel évènement", new_event_path, class:"spec_btn mb-5", method: :get %></div

app/views/events/new.html.erb
</br><h1> Créer un évènement </h1></br>

<div class="card-position">
<div class="card" style="width: 40rem;">

  <%= form_for @event do |f| %>

      <div class="form-group mt-4">
        <label>Nom de l'évènement</label>
        <%= f.text_field :title, class: 'form-control m-2' %>
      </div>

      <div class="form-group">
        <label>Description de l'évènement</label>
        <%= f.text_area :description, class: 'form-control m-2' %>
      </div>

      <div class="form-group">
        <label>Lieu de l'évènement</label>
        <%= f.text_area :location, class: 'form-control m-2' %>
      </div>

      <div class="form-group">
        </br><label>Image de l'évènement</label>
        <%= f.file_field :event_picture, multipart:true %>
      </div></br>


      <div class="form-group">
        <label>Prix de l'évènement</label>
        <%= f.number_field :price, min: 1, max: 1000, step: 1, class: 'form-control m-2' %>
      </div>
      
      <div class="form-group">
        <label>Date de début</label>
        <%= f.datetime_field :start_date, class: 'form-control m-4 custom-datetime-field' %>
      </div>

      <div class="form-group">
        <label>Durée de l'évènement</label>
        <%= f.number_field :duration, min: 0, step: 5, class: 'form-control m-2' %>
      </div>

      <div class="form_group" data: { turbo: "false" }>
        <button type="submit" class="btn btn-primary m-2"> Créer l'évènement</button>
      </div>

  <% end %>
  </div>
</div>

app/views/events/show.html.erb
<h2 class="mt-4"> Détails de l'évènement </h2>

<div class="card mt-4" style="width: 35rem;">
  <div class="card-body">
    <p> <span style="color: blue;">L'évènement est proposé par : </span><%= @event.administrator.first_name %> <%= @event.administrator.last_name %></p>

    <p> <span style="color: blue;">Titre : </span><%= @event.title %></p>

    <p> <span style="color: blue;">Description : </span><%= @event.description %></p>

    <p> <span style="color: blue;">Nombre d'inscrit : </span><%= @event.attendees.count %></p>

    <p> <span style="color: blue;">Créateur de l'évènement : </span><%= @event.administrator.email %></p>

    <p> <span style="color: blue;">Date de début de l'évènement : </span><%= @event.start_date.strftime("%d %B %Y, %H:%M") %></p>

    <p> <span style="color: blue;">Date de fin de l'évènement : </span><%= @event.end_date.strftime("%d %B %Y, %H:%M") %></p>

    <p> <span style="color: blue;">Lieu de l'évènement : </span><%= @event.location %></p>

    <p> <span style="color: blue;">Prix : </span><%= @event.price %> euros</p> 

    <% if @event.event_picture.attached? %>
        <%= image_tag @event.event_picture, width: "50%", style:"border-radius: 15px;" %>
    <% end %>

    <!-- Affichage en fonction du statut de l'utilisateur connecté -->

    <% if user_signed_in? == false %>
    <p class= "text-danger"> Connecte-toi pour me donner de l'argent !</p>

    <% elsif user_signed_in? && current_user.id == @event.administrator.id %>
    <%= button_to "Mon espace évènement", event_attendances_path(@event), class: "btn btn-success m-3", method: :get %>

      <% if @event.event_picture.attached? %>
      <!-- Rien à indiquer, la photo est affichée plus haut. -->
      <% else %>
        <p>=== Il n'y a pas encore d'image liée à cet évènement ===</p>
      <% end %>
      <h3 class="mb-3">Changer La photo de l'évènement</h3>
      <%= form_tag event_event_pictures_path(@event), multipart: true do %>
        <%= file_field_tag :event_picture %>
        <%= submit_tag "mettre à jour", class:"btn-pic" %>
      <% end %>
    <% elsif user_signed_in? && current_user != @event.administrator_id && @registered == false %>
    <%= button_to "S'inscrire à l'évènement", new_event_attendance_path(@event), class: "btn btn-primary m-3", method: :get %>

    <% else %>
    <p class= "text-primary"> Vous êtes déjà inscrit à l'évènement !</p>

    <% end %>
  </div>
</div>