config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show]

  resources :events do
    resources :attendances
    resources :event_pictures, only: [:create]
    patch :update_true, on: :member
    patch :update_false, on: :member
  end

  root to: 'events#index'

  namespace :admin do
      root to: 'users#index'
      resources :users, :events, :attendances
  end

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :welcome_send

  has_many :attendances, foreign_key: 'attendee_id', class_name: "Attendance", dependent: :destroy
  has_many :events, through: :attendances
  has_many :events, foreign_key: 'administrator_id', class_name: "Event", dependent: :destroy

  validates :description, presence:true
  validates :first_name, presence:true
  validates :last_name, presence:true

  def attendee?
    attendances.count > 0
  end

  def administrator?
    events.count > 0
  end
  
  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :check_if_admin

  def index
    @users = User.all
  end

  def destroy
    @user =User.find(params['id'])
    @user.delete
    flash[:alert] = "Compte supprimé !"
    redirect_to root_path
  end

  private

  def check_if_admin
    unless current_user&.is_admin
      flash[:alert] = "Action réservée aux administrateurs !"
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user
  before_action :authenticate_administrator

  def show
    @user = User.find(params['id'])
  end

  private

  def authenticate_user
    unless current_user
      flash[:alert] = "Merci de vous connecter pour voir votre profil"
      redirect_to new_user_session_path
    end
  end

  def authenticate_administrator
    unless current_user == User.find(params['id'])
      flash[:alert] = "Vous ne pouvez accéder qu'à votre profil"
      redirect_to root_path
    end
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<h1> Je suis grooooot... euh... admin </h1>



<p> Voici la liste des utilisateurs </p>


<div class="card w-50">
  <div class="card-body">
    <table style="width: 100%">
    <colgroup>
      <col span="1" style="width: 20%;">
      <col span="2" style="width: 20%;">
      <col span="3" style="width: 30%;">
      <col span="4" style="width: 15%;">
      <col span="5" style="width: 15%;">
    </colgroup>
    <thead>
      <tr>
        <th>Nom</th>
        <th>Prénom</th>
        <th>Email</th>
        <th>Rôle</th>
        <th>Suppression</th>
      </tr>
    </thead>
    <% @users.each do |user| %>
      <tbody>
      <th><%= user.first_name %></th>
      <th><%= user.last_name %></th>
      <th><%= user.email %></th>
      <th><% if user.is_admin %> Admin <% else %> Membre <% end %></th>
      <th><%= button_to "Supprimer", admin_user_path(user), class:'btn btn-danger', form: { data: { turbo_confirm: "Es-tu sur de vouloir supprimer cet utilisateur ?" } }, method: :delete %></th>
      </tbody>
    <% end %>
    </table>
  </div>
  <%= button_to "Gérer les évènements", admin_events_path, method: :get, class:'btn btn-primary m-3', data: { turbo: "false" } %>

</div>