config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show]

  resources :events do
    resources :attendances
    resources :event_pictures, only: [:create]
    patch :update_true, on: :member
    patch :update_false, on: :member
  end

  root to: 'events#index'

  namespace :admin do
      root to: 'users#index'
      resources :users, :events, :attendances
  end

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>D31Oukonva</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Boostrap -->
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css', integrity: 'sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ', crossorigin: 'anonymous' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <!-- Script font awesome -->
    <script src="https://kit.fontawesome.com/7bec0c7944.js" crossorigin="anonymous"></script>
    <!-- Script pour bootstrap pour faire fonctionner le dropdown -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
    
    <!-- Script pour stripe -->
    <script src="https://js.stripe.com/v3/"></script>

  </head>

  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Oukonva</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "Accueil", root_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Créer un évènement", new_event_path, class:"nav-link" %>
            </li>
          </ul>
        </div>
        <!-- Si aucun utilisateur n'est connecté, les options s'inscrire et se connecter apparaissent -->
        <div class="navbar-nav justify-content-end">
          <% if current_user == nil %>
            <div class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              S'inscrire / Se connecter
              </a>
              <ul class="dropdown-menu">
                <%= link_to "S'inscrire", new_user_registration_path, class:"dropdown-item" %>
                <%= link_to "Se connecter", new_user_session_path, class:"dropdown-item" %>
              </ul>
            </div>
          <!-- Si on est admin -->
            <% elsif current_user.is_admin %>
            <div class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Mon profil (<%= current_user.first_name%> <%= current_user.last_name%>)
              </a>
              <ul class="dropdown-menu">
                <%= link_to "Mon profil", user_path(current_user), class:"dropdown-item" %>
                <%= link_to "Dashboard admin", admin_root_path, class:"dropdown-item" %>
                <%= link_to "Se déconnecter", destroy_user_session_path, class:"dropdown-item",form: { data: { turbo_confirm: "Veux-tu te déconnecter ?" } }, method: :delete %>
              </ul>
          <!-- Si on est connecté  --> 
          <% else %>
            <div class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Mon profil (<%= current_user.first_name%> <%= current_user.last_name%>)
              </a>
              <ul class="dropdown-menu">
                <%= link_to "Mon profil", user_path(current_user), class:"dropdown-item" %>
                <%= link_to "Se déconnecter", destroy_user_session_path, class:"dropdown-item",form: { data: { turbo_confirm: "Veux-tu te déconnecter ?" } }, method: :delete %>
              </ul>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </nav>
  </header>
  <body class="body_css">
    <!-- Pour l'affichage des notices et des alertes -->
    <% if notice %>
      <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <% if alert %>
      <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>